### ISSUE TITLE
gpu_script and updated_gpu_script duplicitive

### ISSUE THREAD

**Issue by osullik** [UMD-ARLIS/Graph-Benchmarking-Project#19]
[gpu_script](https://github.com/UMD-ARLIS/Graph-Benchmarking-Project/blob/cleaned_branch/Code/Data_Analysis/gpu_script.py) is duplicated by [updated_gpu_script.py](https://github.com/UMD-ARLIS/Graph-Benchmarking-Project/blob/cleaned_branch/Code/Data_Analysis/updated_gpu_script.py)

Merge scripts, delete one or document how they are different & update to give more informative names. 

Let the git commits do the version control for us.

**Comment by osullik** [comment]
Soon to be deprecated and merged with the "Experiment" class, which has basic unit test coverage built in.

**Comment by nani-r** [comment]
Removed gpu_script.py for redundancy
