### ISSUE TITLE
Find and implement an operational version of the Parallel Louvain algorithm for CPU.

### ISSUE THREAD

**Issue by amirmghaemi** [UMD-ARLIS/Graph-Benchmarking-Project#2]
Find and implement an operational version of the [Parallel Louvain algorithm for CPU](https://github.com/UMD-ARLIS/Graph-Benchmarking-Project/tree/main/Code/Graph_Problems/CommunityDetection/Louvian/Parallel/CPU). We have a couple in there that don’t work, but it might be easiest to blow it away and try again. Preference is for a shared memory implementation, but if all we can get working is distributed memory, I’m sure we’ll work it out. In fact, [these two approaches to parallelizing](https://www.sjsu.edu/people/robert.chun/courses/cs159/s0/Day-10---Overview-MPI-vs-OpenMP.pdf) are probably worth implementing separately, given that they will incur different overheads for network traffic, etc. 

This is likely to include: 
1. Find an open-source Louvain shared memory implementation and get it working on the server
2. [optional] Find an open-source Louvain distributed memory implementation and get it working on the server. 
3. Test it with a few of the datasets located on the server. 
4. Extract it into our git repository & create make files for optimized and debug modes. 
5. Add any required instrumentation so that we can count traversals. 
6. Add any required instrumentation to measure the impact of latency induced by moving data between worker nodes. 
7. Add docco related to the source of code, relevant paper, licensing material etc.

**Comment by vrife** [comment]
Updates thus far:

1. [USC ](https://github.com/usc-cloud/parallel-louvain-modularity/tree/master) implementation is full of undocumented holes which have proven impossible to piece together after several separate efforts from several of us
2. [Ghosh](https://github.com/ECP-ExaGraph/vite) implementation has some "Integer divide-by-zero" error even for the simplest graphs on the server which is a rabbit hole too deep to follow
3. Re-directing effort to implementing parallel shared-memory Leiden community detection for CPU to see if there's any luck [there](https://github.com/CxVercility/ParallelLeiden)

**Comment by vrife** [comment]
Made louvain_update branch with a working implementation and examples of Ghosh's vite
