### ISSUE TITLE
Add Louvain CPU to the Repo. 

### ISSUE THREAD

**Issue by osullik** [UMD-ARLIS/Graph-Benchmarking-Project#40]
Uncompiled Louvain CPU code needs to be added to the Git Repo: 

https://github.com/UMD-ARLIS/Graph-Benchmarking-Project/tree/main/Code/Graph_Problems/CommunityDetection/Louvian

Notes: 
- It should NOT be a nested git repo, but cleaned up and added as a sub-component of ours. 
- It should include relevant licencing and citiation
- It should include compilation instructions and relevant unit tests.

**Comment by vrife** [comment]
Done
